[build]
  publish = "out"
  command = "npm run build && npm run export"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  NEXT_TELEMETRY_DISABLED = "1"

[context.production.environment]
  NEXT_PUBLIC_GA_TRACKING_ID = "G-XXXXXXXXXX"
  NEXT_PUBLIC_APP_URL = "https://vivinjayanth.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_GA_TRACKING_ID = ""
  NEXT_PUBLIC_APP_URL = "$DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  NEXT_PUBLIC_GA_TRACKING_ID = ""
  NEXT_PUBLIC_APP_URL = "$DEPLOY_PRIME_URL"

# Redirect rules
[[redirects]]
  from = "/github"
  to = "https://github.com/Vivinjayanth"
  status = 301

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/vivin-jayanth-a-m"
  status = 301

[[redirects]]
  from = "/resume"
  to = "/resume.pdf"
  status = 301

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (if you add contact forms later)
[[forms]]
  name = "contact"
  
# Edge functions (optional - for advanced features)
[[edge_functions]]
  function = "analytics"
  path = "/*"
